### ISSUE TITLE
Idea - Localization

### ISSUE THREAD

**Issue by wasyady** [GabeHirakawa/SpeakToAll#1]
Can you make language support ?  

Thank you in advance! :blush:

**Comment by GabeHirakawa** [comment]
I can make it ready for localization, however, it will be on the server operator or someone else to actually translate the values.

**Comment by GabeHirakawa** [comment]
I've released the code for the localization support. I have not compiled the plugin yet as I am trying to solve it with CI. 
For now, this issue will be closed.
